### ISSUE TITLE
Do you know the password to build .rar?

### ISSUE THREAD

**Issue by Williamjimus** [Cracked5pider/conti_locker#1]
Do you know the password to /conti_locker/Release/builder.rar?

**Comment by Cracked5pider** [comment]
no

**Comment by Williamjimus** [comment]
May I ask you some questions?




| |
163
|
|
***@***.***
|

Signature is customized by Netease Mail Master

On 10/25/2022 20:01, C5pider wrote:

Closed #1 as completed.
